package pojo;
// Generated Mar 17, 2015 7:23:33 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private AccountId id;
     private Instructor instructor;
     private Student student;
     private String fulName;
     private int userName;
     private String password;
     private boolean accountType;

    public Account() {
    }

	
    public Account(AccountId id, Instructor instructor, Student student, int userName, String password, boolean accountType) {
        this.id = id;
        this.instructor = instructor;
        this.student = student;
        this.userName = userName;
        this.password = password;
        this.accountType = accountType;
    }
    public Account(AccountId id, Instructor instructor, Student student, String fulName, int userName, String password, boolean accountType) {
       this.id = id;
       this.instructor = instructor;
       this.student = student;
       this.fulName = fulName;
       this.userName = userName;
       this.password = password;
       this.accountType = accountType;
    }
   
    public AccountId getId() {
        return this.id;
    }
    
    public void setId(AccountId id) {
        this.id = id;
    }
    public Instructor getInstructor() {
        return this.instructor;
    }
    
    public void setInstructor(Instructor instructor) {
        this.instructor = instructor;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getFulName() {
        return this.fulName;
    }
    
    public void setFulName(String fulName) {
        this.fulName = fulName;
    }
    public int getUserName() {
        return this.userName;
    }
    
    public void setUserName(int userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(boolean accountType) {
        this.accountType = accountType;
    }




}


