package pojo;
// Generated Mar 20, 2015 1:24:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AssesmentQueue generated by hbm2java
 */
public class AssesmentQueue  implements java.io.Serializable {


     private int assesmentQueueId;
     private Lab lab;
     private Set labs = new HashSet(0);
     private Set requestAssesments = new HashSet(0);

    public AssesmentQueue() {
    }

	
    public AssesmentQueue(int assesmentQueueId) {
        this.assesmentQueueId = assesmentQueueId;
    }
    public AssesmentQueue(int assesmentQueueId, Lab lab, Set labs, Set requestAssesments) {
       this.assesmentQueueId = assesmentQueueId;
       this.lab = lab;
       this.labs = labs;
       this.requestAssesments = requestAssesments;
    }
   
    public int getAssesmentQueueId() {
        return this.assesmentQueueId;
    }
    
    public void setAssesmentQueueId(int assesmentQueueId) {
        this.assesmentQueueId = assesmentQueueId;
    }
    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }
    public Set getRequestAssesments() {
        return this.requestAssesments;
    }
    
    public void setRequestAssesments(Set requestAssesments) {
        this.requestAssesments = requestAssesments;
    }




}


