package pojo;
// Generated Mar 23, 2015 7:12:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AssesmentQueue generated by hbm2java
 */
public class AssesmentQueue  implements java.io.Serializable {


     private Integer assesmentQueueId;
     private boolean activated;
     private Set requestAssesments = new HashSet(0);
     private Set labs = new HashSet(0);

    public AssesmentQueue() {
    }

	
    public AssesmentQueue(boolean activated) {
        this.activated = activated;
    }
    public AssesmentQueue(boolean activated, Set requestAssesments, Set labs) {
       this.activated = activated;
       this.requestAssesments = requestAssesments;
       this.labs = labs;
    }
   
    public Integer getAssesmentQueueId() {
        return this.assesmentQueueId;
    }
    
    public void setAssesmentQueueId(Integer assesmentQueueId) {
        this.assesmentQueueId = assesmentQueueId;
    }
    public boolean isActivated() {
        return this.activated;
    }
    
    public void setActivated(boolean activated) {
        this.activated = activated;
    }
    public Set getRequestAssesments() {
        return this.requestAssesments;
    }
    
    public void setRequestAssesments(Set requestAssesments) {
        this.requestAssesments = requestAssesments;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }




}


