package pojo;
// Generated Mar 23, 2015 4:20:09 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer courseId;
     private String name;
     private boolean activated;
     private Set courseHasGroupses = new HashSet(0);

    public Course() {
    }

	
    public Course(String name, boolean activated) {
        this.name = name;
        this.activated = activated;
    }
    public Course(String name, boolean activated, Set courseHasGroupses) {
       this.name = name;
       this.activated = activated;
       this.courseHasGroupses = courseHasGroupses;
    }
   
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isActivated() {
        return this.activated;
    }
    
    public void setActivated(boolean activated) {
        this.activated = activated;
    }
    public Set getCourseHasGroupses() {
        return this.courseHasGroupses;
    }
    
    public void setCourseHasGroupses(Set courseHasGroupses) {
        this.courseHasGroupses = courseHasGroupses;
    }




}


