package pojo;
// Generated Mar 17, 2015 7:23:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DileveryQueue generated by hbm2java
 */
public class DileveryQueue  implements java.io.Serializable {


     private int qileveryQueueId;
     private Set requestDeliveries = new HashSet(0);

    public DileveryQueue() {
    }

	
    public DileveryQueue(int qileveryQueueId) {
        this.qileveryQueueId = qileveryQueueId;
    }
    public DileveryQueue(int qileveryQueueId, Set requestDeliveries) {
       this.qileveryQueueId = qileveryQueueId;
       this.requestDeliveries = requestDeliveries;
    }
   
    public int getQileveryQueueId() {
        return this.qileveryQueueId;
    }
    
    public void setQileveryQueueId(int qileveryQueueId) {
        this.qileveryQueueId = qileveryQueueId;
    }
    public Set getRequestDeliveries() {
        return this.requestDeliveries;
    }
    
    public void setRequestDeliveries(Set requestDeliveries) {
        this.requestDeliveries = requestDeliveries;
    }




}


