package pojo;
// Generated Mar 22, 2015 11:45:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DileveryQueue generated by hbm2java
 */
public class DileveryQueue  implements java.io.Serializable {


     private Integer dileveryQueueId;
     private boolean activated;
     private Set students = new HashSet(0);
     private Set labs = new HashSet(0);

    public DileveryQueue() {
    }

	
    public DileveryQueue(boolean activated) {
        this.activated = activated;
    }
    public DileveryQueue(boolean activated, Set students, Set labs) {
       this.activated = activated;
       this.students = students;
       this.labs = labs;
    }
   
    public Integer getDileveryQueueId() {
        return this.dileveryQueueId;
    }
    
    public void setDileveryQueueId(Integer dileveryQueueId) {
        this.dileveryQueueId = dileveryQueueId;
    }
    public boolean isActivated() {
        return this.activated;
    }
    
    public void setActivated(boolean activated) {
        this.activated = activated;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }




}


