package pojo;
// Generated Mar 17, 2015 7:23:33 PM by Hibernate Tools 4.3.1



/**
 * InstructorId generated by hbm2java
 */
public class InstructorId  implements java.io.Serializable {


     private int accountId;
     private int instructorId;

    public InstructorId() {
    }

    public InstructorId(int accountId, int instructorId) {
       this.accountId = accountId;
       this.instructorId = instructorId;
    }
   
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public int getInstructorId() {
        return this.instructorId;
    }
    
    public void setInstructorId(int instructorId) {
        this.instructorId = instructorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InstructorId) ) return false;
		 InstructorId castOther = ( InstructorId ) other; 
         
		 return (this.getAccountId()==castOther.getAccountId())
 && (this.getInstructorId()==castOther.getInstructorId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAccountId();
         result = 37 * result + this.getInstructorId();
         return result;
   }   


}


