package pojo;
// Generated Mar 23, 2015 5:28:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private Integer instructorId;
     private String fulName;
     private String userName;
     private String password;
     private boolean activated;
     private Set labs = new HashSet(0);

    public Instructor() {
    }

	
    public Instructor(String userName, String password, boolean activated) {
        this.userName = userName;
        this.password = password;
        this.activated = activated;
    }
    public Instructor(String fulName, String userName, String password, boolean activated, Set labs) {
       this.fulName = fulName;
       this.userName = userName;
       this.password = password;
       this.activated = activated;
       this.labs = labs;
    }
   
    public Integer getInstructorId() {
        return this.instructorId;
    }
    
    public void setInstructorId(Integer instructorId) {
        this.instructorId = instructorId;
    }
    public String getFulName() {
        return this.fulName;
    }
    
    public void setFulName(String fulName) {
        this.fulName = fulName;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isActivated() {
        return this.activated;
    }
    
    public void setActivated(boolean activated) {
        this.activated = activated;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }




}


