package pojo;
// Generated Mar 20, 2015 1:53:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lab generated by hbm2java
 */
public class Lab  implements java.io.Serializable {


     private int labId;
     private AssesmentQueue assesmentQueue;
     private Course course;
     private DileveryQueue dileveryQueue;
     private Date startDate;
     private Date endDate;
     private Set dileveryQueues = new HashSet(0);
     private Set assesmentQueues = new HashSet(0);
     private Set instructors = new HashSet(0);
     private Set assignments = new HashSet(0);

    public Lab() {
    }

	
    public Lab(int labId, Course course, DileveryQueue dileveryQueue) {
        this.labId = labId;
        this.course = course;
        this.dileveryQueue = dileveryQueue;
    }
    public Lab(int labId, AssesmentQueue assesmentQueue, Course course, DileveryQueue dileveryQueue, Date startDate, Date endDate, Set dileveryQueues, Set assesmentQueues, Set instructors, Set assignments) {
       this.labId = labId;
       this.assesmentQueue = assesmentQueue;
       this.course = course;
       this.dileveryQueue = dileveryQueue;
       this.startDate = startDate;
       this.endDate = endDate;
       this.dileveryQueues = dileveryQueues;
       this.assesmentQueues = assesmentQueues;
       this.instructors = instructors;
       this.assignments = assignments;
    }
   
    public int getLabId() {
        return this.labId;
    }
    
    public void setLabId(int labId) {
        this.labId = labId;
    }
    public AssesmentQueue getAssesmentQueue() {
        return this.assesmentQueue;
    }
    
    public void setAssesmentQueue(AssesmentQueue assesmentQueue) {
        this.assesmentQueue = assesmentQueue;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public DileveryQueue getDileveryQueue() {
        return this.dileveryQueue;
    }
    
    public void setDileveryQueue(DileveryQueue dileveryQueue) {
        this.dileveryQueue = dileveryQueue;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Set getDileveryQueues() {
        return this.dileveryQueues;
    }
    
    public void setDileveryQueues(Set dileveryQueues) {
        this.dileveryQueues = dileveryQueues;
    }
    public Set getAssesmentQueues() {
        return this.assesmentQueues;
    }
    
    public void setAssesmentQueues(Set assesmentQueues) {
        this.assesmentQueues = assesmentQueues;
    }
    public Set getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(Set instructors) {
        this.instructors = instructors;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }




}


