package pojo;
// Generated Mar 23, 2015 7:12:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lab generated by hbm2java
 */
public class Lab  implements java.io.Serializable {


     private Integer labId;
     private AssesmentQueue assesmentQueue;
     private CourseHasGroups courseHasGroups;
     private DileveryQueue dileveryQueue;
     private Date startDate;
     private Date endDate;
     private String name;
     private Boolean uploadEnabled;
     private boolean activated;
     private Set instructors = new HashSet(0);
     private Set assignments = new HashSet(0);

    public Lab() {
    }

	
    public Lab(AssesmentQueue assesmentQueue, CourseHasGroups courseHasGroups, DileveryQueue dileveryQueue, String name, boolean activated) {
        this.assesmentQueue = assesmentQueue;
        this.courseHasGroups = courseHasGroups;
        this.dileveryQueue = dileveryQueue;
        this.name = name;
        this.activated = activated;
    }
    public Lab(AssesmentQueue assesmentQueue, CourseHasGroups courseHasGroups, DileveryQueue dileveryQueue, Date startDate, Date endDate, String name, Boolean uploadEnabled, boolean activated, Set instructors, Set assignments) {
       this.assesmentQueue = assesmentQueue;
       this.courseHasGroups = courseHasGroups;
       this.dileveryQueue = dileveryQueue;
       this.startDate = startDate;
       this.endDate = endDate;
       this.name = name;
       this.uploadEnabled = uploadEnabled;
       this.activated = activated;
       this.instructors = instructors;
       this.assignments = assignments;
    }
   
    public Integer getLabId() {
        return this.labId;
    }
    
    public void setLabId(Integer labId) {
        this.labId = labId;
    }
    public AssesmentQueue getAssesmentQueue() {
        return this.assesmentQueue;
    }
    
    public void setAssesmentQueue(AssesmentQueue assesmentQueue) {
        this.assesmentQueue = assesmentQueue;
    }
    public CourseHasGroups getCourseHasGroups() {
        return this.courseHasGroups;
    }
    
    public void setCourseHasGroups(CourseHasGroups courseHasGroups) {
        this.courseHasGroups = courseHasGroups;
    }
    public DileveryQueue getDileveryQueue() {
        return this.dileveryQueue;
    }
    
    public void setDileveryQueue(DileveryQueue dileveryQueue) {
        this.dileveryQueue = dileveryQueue;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getUploadEnabled() {
        return this.uploadEnabled;
    }
    
    public void setUploadEnabled(Boolean uploadEnabled) {
        this.uploadEnabled = uploadEnabled;
    }
    public boolean isActivated() {
        return this.activated;
    }
    
    public void setActivated(boolean activated) {
        this.activated = activated;
    }
    public Set getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(Set instructors) {
        this.instructors = instructors;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }




}


