package pojo;
// Generated Mar 23, 2015 5:28:46 AM by Hibernate Tools 4.3.1



/**
 * RequestAssesment generated by hbm2java
 */
public class RequestAssesment  implements java.io.Serializable {


     private RequestAssesmentId id;
     private AssesmentQueue assesmentQueue;
     private Student student;
     private int numberOfRequests;
     private boolean existInQueue;

    public RequestAssesment() {
    }

    public RequestAssesment(RequestAssesmentId id, AssesmentQueue assesmentQueue, Student student, int numberOfRequests, boolean existInQueue) {
       this.id = id;
       this.assesmentQueue = assesmentQueue;
       this.student = student;
       this.numberOfRequests = numberOfRequests;
       this.existInQueue = existInQueue;
    }
   
    public RequestAssesmentId getId() {
        return this.id;
    }
    
    public void setId(RequestAssesmentId id) {
        this.id = id;
    }
    public AssesmentQueue getAssesmentQueue() {
        return this.assesmentQueue;
    }
    
    public void setAssesmentQueue(AssesmentQueue assesmentQueue) {
        this.assesmentQueue = assesmentQueue;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public int getNumberOfRequests() {
        return this.numberOfRequests;
    }
    
    public void setNumberOfRequests(int numberOfRequests) {
        this.numberOfRequests = numberOfRequests;
    }
    public boolean isExistInQueue() {
        return this.existInQueue;
    }
    
    public void setExistInQueue(boolean existInQueue) {
        this.existInQueue = existInQueue;
    }




}


