package pojo;
// Generated Mar 20, 2015 1:53:28 PM by Hibernate Tools 4.3.1



/**
 * RequestAssesment generated by hbm2java
 */
public class RequestAssesment  implements java.io.Serializable {


     private RequestAssesmentId id;
     private AssesmentQueue assesmentQueue;
     private Student student;
     private Integer numberOfRequests;

    public RequestAssesment() {
    }

	
    public RequestAssesment(RequestAssesmentId id, AssesmentQueue assesmentQueue, Student student) {
        this.id = id;
        this.assesmentQueue = assesmentQueue;
        this.student = student;
    }
    public RequestAssesment(RequestAssesmentId id, AssesmentQueue assesmentQueue, Student student, Integer numberOfRequests) {
       this.id = id;
       this.assesmentQueue = assesmentQueue;
       this.student = student;
       this.numberOfRequests = numberOfRequests;
    }
   
    public RequestAssesmentId getId() {
        return this.id;
    }
    
    public void setId(RequestAssesmentId id) {
        this.id = id;
    }
    public AssesmentQueue getAssesmentQueue() {
        return this.assesmentQueue;
    }
    
    public void setAssesmentQueue(AssesmentQueue assesmentQueue) {
        this.assesmentQueue = assesmentQueue;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Integer getNumberOfRequests() {
        return this.numberOfRequests;
    }
    
    public void setNumberOfRequests(Integer numberOfRequests) {
        this.numberOfRequests = numberOfRequests;
    }




}


