package pojo;
// Generated Mar 17, 2015 7:23:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private StudentId id;
     private Department department;
     private String fulName;
     private int userName;
     private String password;
     private boolean accountType;
     private Set labgroups = new HashSet(0);
     private Set requestDeliveries = new HashSet(0);
     private Set requestAssesments = new HashSet(0);
     private Set assignments = new HashSet(0);
     private Set accounts = new HashSet(0);

    public Student() {
    }

	
    public Student(StudentId id, Department department, int userName, String password, boolean accountType) {
        this.id = id;
        this.department = department;
        this.userName = userName;
        this.password = password;
        this.accountType = accountType;
    }
    public Student(StudentId id, Department department, String fulName, int userName, String password, boolean accountType, Set labgroups, Set requestDeliveries, Set requestAssesments, Set assignments, Set accounts) {
       this.id = id;
       this.department = department;
       this.fulName = fulName;
       this.userName = userName;
       this.password = password;
       this.accountType = accountType;
       this.labgroups = labgroups;
       this.requestDeliveries = requestDeliveries;
       this.requestAssesments = requestAssesments;
       this.assignments = assignments;
       this.accounts = accounts;
    }
   
    public StudentId getId() {
        return this.id;
    }
    
    public void setId(StudentId id) {
        this.id = id;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getFulName() {
        return this.fulName;
    }
    
    public void setFulName(String fulName) {
        this.fulName = fulName;
    }
    public int getUserName() {
        return this.userName;
    }
    
    public void setUserName(int userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(boolean accountType) {
        this.accountType = accountType;
    }
    public Set getLabgroups() {
        return this.labgroups;
    }
    
    public void setLabgroups(Set labgroups) {
        this.labgroups = labgroups;
    }
    public Set getRequestDeliveries() {
        return this.requestDeliveries;
    }
    
    public void setRequestDeliveries(Set requestDeliveries) {
        this.requestDeliveries = requestDeliveries;
    }
    public Set getRequestAssesments() {
        return this.requestAssesments;
    }
    
    public void setRequestAssesments(Set requestAssesments) {
        this.requestAssesments = requestAssesments;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


