package dto.instructor;
// Generated Mar 20, 2015 1:53:28 PM by Hibernate Tools 4.3.1






/**
 * Assignment generated by hbm2java
 */
public class AssignmentDto{
    private int assignmentId;
    private LabDto lab;
    private StudentDto student;
    private String name;
    private String url;

    public AssignmentDto() {
    }

    public AssignmentDto(LabDto lab, dto.instructor.StudentDto student, String name, String url) {
        this.lab = lab;
        this.student = student;
        this.name = name;
        this.url = url;
    }

    public int getAssignmentId() {
        return assignmentId;
    }

    public LabDto getLab() {
        return lab;
    }

    public dto.instructor.StudentDto getStudent() {
        return student;
    }

    public String getName() {
        return name;
    }

    public String getUrl() {
        return url;
    }

    public void setAssignmentId(int assignmentId) {
        this.assignmentId = assignmentId;
    }

    public void setLab(LabDto lab) {
        this.lab = lab;
    }

    public void setStudent(dto.instructor.StudentDto student) {
        this.student = student;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    
}


