package dto;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1


import pojo.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class AccountDto  implements Dto {


     private int accountId;
     private String fulName;
     private int userName;
     private String password;
     private boolean accountType;
     private Set instructors = new HashSet(0);
     private Set students = new HashSet(0);

    public AccountDto() {
    }

	
    public AccountDto(int accountId, int userName, String password, boolean accountType) {
        this.accountId = accountId;
        this.userName = userName;
        this.password = password;
        this.accountType = accountType;
    }
    public AccountDto(int accountId, String fulName, int userName, String password, boolean accountType, Set instructors, Set students) {
       this.accountId = accountId;
       this.fulName = fulName;
       this.userName = userName;
       this.password = password;
       this.accountType = accountType;
       this.instructors = instructors;
       this.students = students;
    }
   
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public String getFulName() {
        return this.fulName;
    }
    
    public void setFulName(String fulName) {
        this.fulName = fulName;
    }
    public int getUserName() {
        return this.userName;
    }
    
    public void setUserName(int userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(boolean accountType) {
        this.accountType = accountType;
    }
    public Set getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(Set instructors) {
        this.instructors = instructors;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }




}


