package dto;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1


import pojo.*;
import java.util.HashSet;
import java.util.Set;

/**
 * AssesmentQueue generated by hbm2java
 */
public class AssesmentQueueDto  implements Dto {


     private int assesmentQueueId;
     private Set requestAssesments = new HashSet(0);

    public AssesmentQueueDto() {
    }

	
    public AssesmentQueueDto(int assesmentQueueId) {
        this.assesmentQueueId = assesmentQueueId;
    }
    public AssesmentQueueDto(int assesmentQueueId, Set requestAssesments) {
       this.assesmentQueueId = assesmentQueueId;
       this.requestAssesments = requestAssesments;
    }
   
    public int getAssesmentQueueId() {
        return this.assesmentQueueId;
    }
    
    public void setAssesmentQueueId(int assesmentQueueId) {
        this.assesmentQueueId = assesmentQueueId;
    }
    public Set getRequestAssesments() {
        return this.requestAssesments;
    }
    
    public void setRequestAssesments(Set requestAssesments) {
        this.requestAssesments = requestAssesments;
    }




}


