package dto;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1


import pojo.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class CourseDto  implements Dto {


     private int courseId;
     private String name;
     private Set labs = new HashSet(0);
     private Set labgroups = new HashSet(0);

    public CourseDto() {
    }

	
    public CourseDto(int courseId) {
        this.courseId = courseId;
    }
    public CourseDto(int courseId, String name, Set labs, Set labgroups) {
       this.courseId = courseId;
       this.name = name;
       this.labs = labs;
       this.labgroups = labgroups;
    }
   
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }
    public Set getLabgroups() {
        return this.labgroups;
    }
    
    public void setLabgroups(Set labgroups) {
        this.labgroups = labgroups;
    }




}


