package dto;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1


import pojo.*;
import java.util.HashSet;
import java.util.Set;

/**
 * DileveryQueue generated by hbm2java
 */
public class DileveryQueueDto  implements Dto {


     private int qileveryQueueId;
     private Set requestDeliveries = new HashSet(0);

    public DileveryQueueDto() {
    }

	
    public DileveryQueueDto(int qileveryQueueId) {
        this.qileveryQueueId = qileveryQueueId;
    }
    public DileveryQueueDto(int qileveryQueueId, Set requestDeliveries) {
       this.qileveryQueueId = qileveryQueueId;
       this.requestDeliveries = requestDeliveries;
    }
   
    public int getQileveryQueueId() {
        return this.qileveryQueueId;
    }
    
    public void setQileveryQueueId(int qileveryQueueId) {
        this.qileveryQueueId = qileveryQueueId;
    }
    public Set getRequestDeliveries() {
        return this.requestDeliveries;
    }
    
    public void setRequestDeliveries(Set requestDeliveries) {
        this.requestDeliveries = requestDeliveries;
    }




}


