package dto;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1

import pojo.*;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1



/**
 * InstructorIdDto generated by hbm2java
 */
public class InstructorIdDto  implements Dto {


     private int accountId;
     private int instructorId;

    public InstructorIdDto() {
    }

    public InstructorIdDto(int accountId, int instructorId) {
       this.accountId = accountId;
       this.instructorId = instructorId;
    }
   
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public int getInstructorId() {
        return this.instructorId;
    }
    
    public void setInstructorId(int instructorId) {
        this.instructorId = instructorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InstructorIdDto) ) return false;
		 InstructorIdDto castOther = ( InstructorIdDto ) other; 
         
		 return (this.getAccountId()==castOther.getAccountId())
 && (this.getInstructorId()==castOther.getInstructorId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAccountId();
         result = 37 * result + this.getInstructorId();
         return result;
   }   


}


