package dto;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1


import pojo.*;
import java.util.HashSet;
import java.util.Set;

/**
 * InstructorDto generated by hbm2java
 */
public class InstructorDto  implements Dto {


     private InstructorIdDto id;
     private AccountDto account;
     private String fulName;
     private int userName;
     private String password;
     private boolean accountType;
     private Set labs = new HashSet(0);

    public InstructorDto() {
    }

	
    public InstructorDto(InstructorIdDto id, AccountDto account, int userName, String password, boolean accountType) {
        this.id = id;
        this.account = account;
        this.userName = userName;
        this.password = password;
        this.accountType = accountType;
    }
    public InstructorDto(InstructorIdDto id, AccountDto account, String fulName, int userName, String password, boolean accountType, Set labs) {
       this.id = id;
       this.account = account;
       this.fulName = fulName;
       this.userName = userName;
       this.password = password;
       this.accountType = accountType;
       this.labs = labs;
    }
   
    public InstructorIdDto getId() {
        return this.id;
    }
    
    public void setId(InstructorIdDto id) {
        this.id = id;
    }
    public AccountDto getAccount() {
        return this.account;
    }
    
    public void setAccount(AccountDto account) {
        this.account = account;
    }
    public String getFulName() {
        return this.fulName;
    }
    
    public void setFulName(String fulName) {
        this.fulName = fulName;
    }
    public int getUserName() {
        return this.userName;
    }
    
    public void setUserName(int userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(boolean accountType) {
        this.accountType = accountType;
    }
    public Set getLabs() {
        return this.labs;
    }
    
    public void setLabs(Set labs) {
        this.labs = labs;
    }




}


