package dto;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1

import pojo.*;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1



/**
 * RequestAssesmentDto generated by hbm2java
 */
public class RequestAssesmentDto  implements Dto {


     private RequestAssesmentIdDto id;
     private AssesmentQueue assesmentQueue;
     private StudentDto student;
     private Integer numberOfRequests;
     private String labName;

    public RequestAssesmentDto() {
    }

	
    public RequestAssesmentDto(RequestAssesmentIdDto id, AssesmentQueue assesmentQueue, StudentDto student, String labName) {
        this.id = id;
        this.assesmentQueue = assesmentQueue;
        this.student = student;
        this.labName = labName;
    }
    public RequestAssesmentDto(RequestAssesmentIdDto id, AssesmentQueue assesmentQueue, StudentDto student, Integer numberOfRequests, String labName) {
       this.id = id;
       this.assesmentQueue = assesmentQueue;
       this.student = student;
       this.numberOfRequests = numberOfRequests;
       this.labName = labName;
    }
   
    public RequestAssesmentIdDto getId() {
        return this.id;
    }
    
    public void setId(RequestAssesmentIdDto id) {
        this.id = id;
    }
    public AssesmentQueue getAssesmentQueue() {
        return this.assesmentQueue;
    }
    
    public void setAssesmentQueue(AssesmentQueue assesmentQueue) {
        this.assesmentQueue = assesmentQueue;
    }
    public StudentDto getStudent() {
        return this.student;
    }
    
    public void setStudent(StudentDto student) {
        this.student = student;
    }
    public Integer getNumberOfRequests() {
        return this.numberOfRequests;
    }
    
    public void setNumberOfRequests(Integer numberOfRequests) {
        this.numberOfRequests = numberOfRequests;
    }
    public String getLabName() {
        return this.labName;
    }
    
    public void setLabName(String labName) {
        this.labName = labName;
    }




}


