package dto;
// Generated Mar 15, 2015 10:17:48 PM by Hibernate Tools 4.3.1


import pojo.*;
import java.util.HashSet;
import java.util.Set;

/**
 * StudentDto generated by hbm2java
 */
public class StudentDto  implements Dto {


     private StudentIdDto id;
     private AccountDto account;
     private DepartmentDto department;
     private String fulName;
     private int userName;
     private String password;
     private boolean accountType;
     private Set labgroups = new HashSet(0);
     private Set requestDeliveries = new HashSet(0);
     private Set requestAssesments = new HashSet(0);
     private Set assignments = new HashSet(0);

    public StudentDto() {
    }

	
    public StudentDto(StudentIdDto id, AccountDto account, DepartmentDto department, int userName, String password, boolean accountType) {
        this.id = id;
        this.account = account;
        this.department = department;
        this.userName = userName;
        this.password = password;
        this.accountType = accountType;
    }
    public StudentDto(StudentIdDto id, AccountDto account, DepartmentDto department, String fulName, int userName, String password, boolean accountType, Set labgroups, Set requestDeliveries, Set requestAssesments, Set assignments) {
       this.id = id;
       this.account = account;
       this.department = department;
       this.fulName = fulName;
       this.userName = userName;
       this.password = password;
       this.accountType = accountType;
       this.labgroups = labgroups;
       this.requestDeliveries = requestDeliveries;
       this.requestAssesments = requestAssesments;
       this.assignments = assignments;
    }
   
    public StudentIdDto getId() {
        return this.id;
    }
    
    public void setId(StudentIdDto id) {
        this.id = id;
    }
    public AccountDto getAccount() {
        return this.account;
    }
    
    public void setAccount(AccountDto account) {
        this.account = account;
    }
    public DepartmentDto getDepartment() {
        return this.department;
    }
    
    public void setDepartment(DepartmentDto department) {
        this.department = department;
    }
    public String getFulName() {
        return this.fulName;
    }
    
    public void setFulName(String fulName) {
        this.fulName = fulName;
    }
    public int getUserName() {
        return this.userName;
    }
    
    public void setUserName(int userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(boolean accountType) {
        this.accountType = accountType;
    }
    public Set getLabgroups() {
        return this.labgroups;
    }
    
    public void setLabgroups(Set labgroups) {
        this.labgroups = labgroups;
    }
    public Set getRequestDeliveries() {
        return this.requestDeliveries;
    }
    
    public void setRequestDeliveries(Set requestDeliveries) {
        this.requestDeliveries = requestDeliveries;
    }
    public Set getRequestAssesments() {
        return this.requestAssesments;
    }
    
    public void setRequestAssesments(Set requestAssesments) {
        this.requestAssesments = requestAssesments;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }




}


